export const LANGS = ['zh', 'en', 'ja', 'ko', 'de', 'uk', 'in', 'br'];

export const T = {
  headline: '把隐私交给 AI 之前，先脱敏',
  headlineEn: 'Redact PII before it reaches an AI',
  trust: '🔒 全部在你的浏览器里运行，数据不上传 · runs locally, nothing uploaded',
  loading: '加载中… · loading',
  ready: '● 已就绪 · ready',
  failed: '⚠ 加载失败 · failed: ',
  tryLabel: '试试 · Try:',
  redact: '一键脱敏 · Redact',
  yourText: '你的原文 · Your text',
  aiSees: 'AI 看到的 · What the AI sees',
  restoredOk: '✓ 还能一字不差地还原 · restored exactly',
  howTitle: '怎么做到的 · How it works',
  steps: ['① 找出隐私信息 · find personal info', '② 换成安全替身 · swap in safe look-alikes', '③ 回复里再换回来 · restore from the reply'],
  badges: ['50+ 类隐私信息', '8 种语言', '可逆还原', '开源 Apache-2.0', '身份证/银行卡校验'],
  limitNote: '⚠ 脱敏移除显式 PII，但不能保证抵御从残留上下文的推理式重识别 · removes explicit PII, not a guarantee against inference-based re-identification',
  llmProof: '真实大模型，零泄漏 · Real AIs, zero leaks',
  llmProvenance: '来源 · Source: ',
  llmCaptionTail: '。非对抗输入下的缓存结果，非绝对保证 · cached reference run, not a guarantee against adversarial input.',
  devFold: '开发者选项 · For developers',
  devInput: '在这里输入或粘贴文本 · type or paste text',
  devStrategyTitle: '每类信息的处理方式 · Per-type handling',
  devNames: '已知姓名（逗号分隔）· known names',
  devLang: '语言 · Languages',
  devSeed: '种子 · seed',
  randomize: '🎲 随机 · Randomize',
  devRun: '脱敏 · Redact',
  keyJson: '密钥 · Key (JSON)',
  copy: '复制 · Copy',
  redacted: '脱敏后 · Redacted',
  restored: '还原 · Restored',
  streamTitle: '流式处理 · Streaming',
  streamRun: '开始流式 · Stream it',
};
