"""Generate crates/argus-redact-core/data/risk_data.ron from the registry SSOT.

`assess_risk` reads, per (lang, type): pipl_articles, gdpr_special_category,
hipaa_phi_category — already resolved on each registered PIITypeDef. It also reads
two compliance constants: PIPL_SENSITIVE_PI and PIPL_SORT_ORDER. We serialize all
of these so the Rust port has byte-identical inputs. The registry is the single
source of truth; the parity gate (tests/architecture/test_risk_data_parity.py)
fails if the embedded RON drifts.

Run: `make gen-risk-data`  (writes the .ron)
CI:  `make gen-risk-data-check`  (exit 1 on drift)
"""

from __future__ import annotations

import sys

from argus_redact.specs._compliance import PIPL_SENSITIVE_PI, PIPL_SORT_ORDER
from argus_redact.specs._gen_ron import core_data_path, emit_or_check, ron_opt_str, ron_str
from argus_redact.specs.registry import list_types

_OUT = core_data_path("risk_data.ron")


def build_ron() -> str:
    lines: list[str] = []
    lines.append("// GENERATED by argus_redact.specs.gen_risk_data — do not edit by hand.")
    lines.append("// SSOT: the Python registry (specs/*.py). Regenerate: make gen-risk-data")
    lines.append("(")
    lines.append("    types: [")
    for td in list_types():  # registration order (preserves lookup()[0] fallback)
        pipl = ", ".join(ron_str(a) for a in td.pipl_articles)
        lines.append(
            "        ("
            f"lang: {ron_str(td.lang)}, "
            f"name: {ron_str(td.name)}, "
            f"pipl_articles: [{pipl}], "
            f"gdpr_special_category: {str(td.gdpr_special_category).lower()}, "
            f"gdpr_art10: {str(td.gdpr_art10).lower()}, "
            f"hipaa_phi_category: {ron_opt_str(td.hipaa_phi_category)}"
            "),"
        )
    lines.append("    ],")
    sensitive = ", ".join(ron_str(x) for x in sorted(PIPL_SENSITIVE_PI))
    lines.append(f"    pipl_sensitive_pi: [{sensitive}],")
    lines.append("    pipl_sort_order: [")
    for art, rank in sorted(PIPL_SORT_ORDER.items(), key=lambda kv: kv[1]):
        lines.append(f"        ({ron_str(art)}, {rank}),")
    lines.append("    ],")
    lines.append(")")
    return "\n".join(lines) + "\n"


def main() -> int:
    return emit_or_check(
        _OUT,
        build_ron(),
        sys.argv,
        human_name="risk_data.ron",
        out_of_sync_msg="risk_data.ron is out of sync with the registry. Run: make gen-risk-data",
    )


if __name__ == "__main__":
    sys.exit(main())
