"""Tests for PIITypeDef.to_patterns() — spec-derived patterns should match
the same inputs as hand-written patterns."""

from argus_redact.lang.shared.patterns import PATTERNS as SHARED
from argus_redact.lang.zh.patterns import PATTERNS as ZH_HAND_WRITTEN
from argus_redact.pure.patterns import match_patterns
from argus_redact.specs import list_types
from argus_redact.specs import zh as _zh  # noqa: F401

# Test inputs covering all types
TEST_INPUTS = [
    # phone
    "手机13812345678",
    "电话138 1234 5678",
    "号码138-1234-5678",
    # phone_landline
    "座机010-12345678",
    "0755-12345678",
    # id_number
    "身份证号110101199003074610",
    "证件号 110101 19900307 4610",
    "11010119900307002X",
    # bank_card
    "银行卡4111111111111111",
    "卡号6217001234567890",
    # passport
    "护照号E12345678",
    # license_plate
    "车牌京A12345",
    "粤B·12345",
    # address
    "北京市朝阳区建国路100号",
    "广东省深圳市南山区科技路1号",
    "朝阳建国路100号",
    # person
    "客户张三的手机号",
    "联系人王小明",
    "赵敏女士已确认",
    # email (shared)
    "邮箱test@qq.com",
    # negative
    "今天天气不错",
    "版本号v2.0.1",
]


class TestToPatterns:
    # Since v0.7.1, PIITypeDef.to_patterns() derives from the Rust core (SSOT),
    # filtered to the typedef's own `name`. A zh typedef therefore produces no
    # pattern only when the core emits nothing under that name:
    #   - person  : NER-only, no Layer-1 regex
    #   - age     : zh has no core `age` pattern (age is a shared/core type)
    #   - phone_landline : its core pattern is keyed under type="phone", not
    #                      "phone_landline", so filtering by its own name is empty
    #   - hobby          : framework-detected (evidence_detector + hobbies.rs),
    #                      no regex pattern — validated by tests/core/test_hobby_detect.py
    _NO_CORE_PATTERN = {"person", "age", "phone_landline", "hobby"}

    # Types whose detection is exercised at the `phone`/shared level rather than
    # under their own typedef name — excluded from the cross-pattern parity check
    # below to keep its set arithmetic stable across the core migration.
    _PATTERNS_IN_SOURCE = {
        "person",
        "phone_landline",
        "age",
        "email",
        "ip_address",
        "mac_address",
    }

    def test_spec_patterns_should_exist(self):
        """Every zh spec that maps to a core pattern under its own name should
        derive at least one pattern from the core."""
        for typedef in list_types("zh"):
            if typedef.name in self._NO_CORE_PATTERN:
                continue
            patterns = typedef.to_patterns()
            assert len(patterns) >= 1, f"{typedef.name} produced no patterns"

    def test_spec_patterns_should_have_required_keys(self):
        """Each generated pattern dict must have type, label, pattern."""
        for typedef in list_types("zh"):
            for pat in typedef.to_patterns():
                assert "type" in pat
                assert "label" in pat
                assert "pattern" in pat
                assert pat["type"] == typedef.name or (
                    typedef.name == "phone_landline" and pat["type"] == "phone"
                )

    def test_spec_patterns_should_match_same_as_hand_written(self):
        """For every test input, spec-derived patterns should detect
        the same entity types as the hand-written patterns."""
        spec_patterns = []
        for typedef in list_types("zh"):
            spec_patterns.extend(typedef.to_patterns())

        for text in TEST_INPUTS:
            hand = {r.type for r in match_patterns(text, ZH_HAND_WRITTEN + SHARED)[0]}
            spec = {r.type for r in match_patterns(text, spec_patterns + SHARED)[0]}
            # Exclude types managed in source (not generated by specs)
            hand -= self._PATTERNS_IN_SOURCE
            spec -= self._PATTERNS_IN_SOURCE
            assert hand == spec, f"Mismatch on '{text[:40]}...': hand={hand} spec={spec}"

    def test_build_patterns_replaces_hand_written(self):
        """build_patterns('zh') should be a drop-in replacement."""
        from argus_redact.specs.zh import build_patterns

        built = build_patterns()

        for text in TEST_INPUTS:
            hand = {
                (r.type, r.text)
                for r in match_patterns(text, ZH_HAND_WRITTEN)[0]
                if r.type not in self._PATTERNS_IN_SOURCE
            }
            spec = {
                (r.type, r.text)
                for r in match_patterns(text, built)[0]
                if r.type not in self._PATTERNS_IN_SOURCE
            }
            assert hand == spec, (
                f"Mismatch on '{text[:40]}...': hand-only={hand - spec} spec-only={spec - hand}"
            )


class TestToPatternsEn:
    """Parity test for specs/en.py — every en typedef derives its pattern(s)
    from the Rust core (SSOT) via PIITypeDef.to_patterns().

    Unlike zh, en has no `_NO_CORE_PATTERN` allowlist beyond `person`: every en
    typedef maps to a core pattern under its own name. The exception is `person`,
    which is NER-only and produces no core pattern.
    """

    _NER_ONLY = {"person"}

    def test_spec_patterns_should_exist(self):
        """Every en spec except NER-only types should produce at least one pattern."""
        for typedef in list_types("en"):
            if typedef.name in self._NER_ONLY:
                continue
            patterns = typedef.to_patterns()
            assert len(patterns) >= 1, f"en/{typedef.name} produced no patterns"

    def test_spec_patterns_should_have_required_keys(self):
        for typedef in list_types("en"):
            for pat in typedef.to_patterns():
                assert "type" in pat
                assert "label" in pat
                assert "pattern" in pat
                assert pat["type"] == typedef.name

    def test_build_patterns_provides_drop_in_for_lang_module(self):
        """specs/en.py:build_patterns() detects identically to lang/en/patterns.py:PATTERNS.

        Since v0.7.1 ``lang/en/patterns.py`` reads from the Rust core SSOT rather
        than re-exporting the spec, so the dict SHAPES differ (the core emits a
        ``validator`` name string where the spec carries a ``validate`` callable).
        The contract that survives the migration is BEHAVIORAL: both pattern lists
        produce the same detections. Equivalent type counts also guard against a
        spec/core skew.
        """
        from argus_redact.lang.en.patterns import PATTERNS as EN_PATTERNS
        from argus_redact.specs.en import build_patterns

        built = build_patterns()
        assert len(built) == len(EN_PATTERNS), (
            "spec and core must expose the same number of en patterns"
        )
        for typedef in list_types("en"):
            for text in typedef.examples:
                spec = {
                    (r.type, r.text) for r in match_patterns(text, built)[0]
                }
                core = {
                    (r.type, r.text) for r in match_patterns(text, EN_PATTERNS)[0]
                }
                assert spec == core, (
                    f"detection drift on '{text[:40]}...': "
                    f"spec-only={spec - core} core-only={core - spec}"
                )


from tests.conftest import load_examples

# Inputs for the shared parity test: positive fixtures + one negative sanity check.
CREDENTIAL_INPUTS = [
    fx["input"] for fx in load_examples("shared_secrets.json") if fx["should_match"]
] + ["just a plain sentence with no credentials"]


class TestToPatternsShared:
    """Parity test for specs/shared.py — spec-derived _patterns must match the
    hand-written PATTERNS in lang/shared/patterns.py on credential inputs."""

    # Shared types whose detection regex lives in lang/shared/patterns.py rather
    # than the spec _patterns (mirrors zh's _PATTERNS_IN_SOURCE convention).
    # phone_landline / date / url are NER/Presidio-sourced; no spec-level _patterns.
    _PATTERNS_IN_SOURCE = {"email", "ip_address", "mac_address", "phone_landline", "date", "url"}

    def test_spec_patterns_should_exist(self):
        """Every shared spec should produce at least one pattern."""
        for typedef in list_types("shared"):
            if typedef.name in self._PATTERNS_IN_SOURCE:
                continue
            patterns = typedef.to_patterns()
            assert len(patterns) >= 1, f"{typedef.name} produced no patterns"

    def test_spec_patterns_should_have_required_keys(self):
        """Each generated pattern dict must have type, label, pattern; type matches spec name."""
        for typedef in list_types("shared"):
            for pat in typedef.to_patterns():
                assert "type" in pat
                assert "label" in pat
                assert "pattern" in pat
                assert pat["type"] == typedef.name

    def test_spec_patterns_should_match_same_as_hand_written(self):
        """Spec-derived shared patterns must detect the same types as hand-written."""
        spec_patterns = []
        for typedef in list_types("shared"):
            spec_patterns.extend(typedef.to_patterns())

        for text in CREDENTIAL_INPUTS:
            hand = {r.type for r in match_patterns(text, SHARED)[0]}
            spec = {r.type for r in match_patterns(text, spec_patterns)[0]}
            # Exclude PATTERNS_IN_SOURCE types that don't have spec-derived patterns
            hand -= self._PATTERNS_IN_SOURCE
            spec -= self._PATTERNS_IN_SOURCE
            assert hand == spec, f"Mismatch on '{text[:50]}...': hand={hand} spec={spec}"
